# Generated by Django 2.2.10 on 2020-04-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_read_clg', 'Can read clg'), ('can_read_dpt', 'Can read dpt')),
            },
        ),
        migrations.CreateModel(
            name='CollegeProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_write_clg', 'Can write clg'), ('can_write_dpt', 'Can write dpt'), ('can_read_dpt', 'Can read dpt'), ('can_read_clg', 'Can read clg')),
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
                ('schoolName', models.TextField(max_length=200)),
                ('departmentName', models.TextField(max_length=200)),
                ('pubDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='DeptConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_read_dpt', 'Can read dpt'),),
            },
        ),
        migrations.CreateModel(
            name='DeptProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_write_dpt', 'Can write dpt'), ('can_read_dpt', 'Can read dpt')),
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_view_all', 'Can view all'),),
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=200)),
                ('password', models.TextField(max_length=200)),
                ('invitecode', models.CharField(max_length=200)),
                ('pubDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='SystemConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_read_sys', 'Can read sys'), ('can_read_uni', 'Can read uni'), ('can_read_clg', 'Can read clg'), ('can_read_dpt', 'Can read dpt')),
            },
        ),
        migrations.CreateModel(
            name='SystemProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_write_sys', 'Can write sys'), ('can_write_uni', 'Can write uni'), ('can_write_clg', 'Can write clg'), ('can_write_dpt', 'Can write dpt'), ('can_read_dpt', 'Can read dpt'), ('can_read_clg', 'Can read clg'), ('can_read_uni', 'Can read uni'), ('can_read_sys', 'Can read sys')),
            },
        ),
        migrations.CreateModel(
            name='UnivConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_read_uni', 'Can read uni'), ('can_read_clg', 'Can read clg'), ('can_read_dpt', 'Can read dpt')),
            },
        ),
        migrations.CreateModel(
            name='UnivProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_write_uni', 'Can write uni'), ('can_write_clg', 'Can write clg'), ('can_write_dpt', 'Can write dpt'), ('can_read_dpt', 'Can read dpt'), ('can_read_clg', 'Can read clg'), ('can_read_uni', 'Can read uni')),
            },
        ),
    ]
