# Generated by Django 2.2.10 on 2020-02-21 20:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
                ('schoolName', models.TextField(max_length=200)),
                ('departmentName', models.TextField(max_length=200)),
                ('markovModel', models.CharField(max_length=200)),
                ('pubDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='DeptConsumer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_member', 'can_view'),),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=200)),
                ('password', models.TextField(max_length=200)),
                ('invitecode', models.CharField(max_length=200)),
                ('pubDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeConsumer',
            fields=[
                ('deptconsumer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insert2DB.DeptConsumer')),
            ],
            options={
                'permissions': (('can_upload', 'Friendly message'),),
            },
            bases=('insert2DB.deptconsumer',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeptProvider',
            fields=[
                ('deptconsumer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insert2DB.DeptConsumer')),
            ],
            options={
                'permissions': (('can_view_all', 'Friendly message'),),
            },
            bases=('insert2DB.deptconsumer',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CollegeProvider',
            fields=[
                ('deptprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insert2DB.DeptProvider')),
            ],
            options={
                'permissions': (('can_view_all', 'Friendly message'),),
            },
            bases=('insert2DB.deptprovider',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UnivConsumer',
            fields=[
                ('collegeconsumer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insert2DB.CollegeConsumer')),
            ],
            options={
                'permissions': (('can_view_school', 'Friendly message'),),
            },
            bases=('insert2DB.collegeconsumer',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SystemConsumer',
            fields=[
                ('univconsumer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insert2DB.UnivConsumer')),
            ],
            options={
                'permissions': (('can_view_all', 'Friendly message'),),
            },
            bases=('insert2DB.univconsumer',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UnivProvider',
            fields=[
                ('collegeprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insert2DB.CollegeProvider')),
            ],
            options={
                'permissions': (('can_view_all', 'Friendly message'),),
            },
            bases=('insert2DB.collegeprovider',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SystemProvider',
            fields=[
                ('univprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insert2DB.UnivProvider')),
            ],
            options={
                'permissions': (('can_view_all', 'Friendly message'),),
            },
            bases=('insert2DB.univprovider',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('systemprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insert2DB.SystemProvider')),
            ],
            options={
                'permissions': (('can_view_all', 'Friendly message'),),
            },
            bases=('insert2DB.systemprovider',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
