# Generated by Django 2.2.10 on 2020-04-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insert2DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegeconsumer',
            options={'permissions': (('can_read_clg', 'Friendly message'),)},
        ),
        migrations.AlterModelOptions(
            name='collegeprovider',
            options={'permissions': (('can_write_clg', 'Friendly message'),)},
        ),
        migrations.AlterModelOptions(
            name='deptconsumer',
            options={'permissions': (('can_read_dpt', 'Friendly message'),)},
        ),
        migrations.AlterModelOptions(
            name='deptprovider',
            options={'permissions': (('can_write_dpt', 'Friendly message'),)},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'permissions': (('can_view_all', 'can_write_all'),)},
        ),
        migrations.AlterModelOptions(
            name='systemconsumer',
            options={'permissions': (('can_read_sys', 'Friendly message'),)},
        ),
        migrations.AlterModelOptions(
            name='systemprovider',
            options={'permissions': (('can_write_sys', 'Friendly message'),)},
        ),
        migrations.AlterModelOptions(
            name='univconsumer',
            options={'permissions': (('can_read_uni', 'Friendly message'),)},
        ),
        migrations.AlterModelOptions(
            name='univprovider',
            options={'permissions': (('can_write_uni', 'Friendly message'),)},
        ),
        migrations.RemoveField(
            model_name='data',
            name='markovModel',
        ),
    ]
