# Generated by Django 2.2.10 on 2020-04-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insert2DB', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeptConsumer',
            new_name='DepartmentConsumer',
        ),
        migrations.RenameModel(
            old_name='DeptProvider',
            new_name='DepartmentProvider',
        ),
        migrations.RenameModel(
            old_name='UnivConsumer',
            new_name='UniversityConsumer',
        ),
        migrations.RenameModel(
            old_name='UnivProvider',
            new_name='UniversityProvider',
        ),
    ]
