# Generated by Django 2.2.10 on 2020-04-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insert2DB', '0002_auto_20200423_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.TextField(max_length=200)),
                ('departmentName', models.TextField(max_length=200)),
                ('userProvider', models.TextField(max_length=200)),
                ('typeOfData', models.TextField(max_length=200)),
                ('sigma', models.IntegerField()),
                ('alpha', models.IntegerField()),
                ('beta', models.IntegerField()),
                ('lmbda', models.IntegerField()),
                ('pubDate', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'permissions': (('can_read_dpt', 'Can read dpt'), ('can_read_clg', 'Can read clg'), ('can_read_uni', 'Can read uni'), ('can_read_sys', 'Can read sys')),
            },
        ),
        migrations.DeleteModel(
            name='CollegeConsumer',
        ),
        migrations.DeleteModel(
            name='CollegeProvider',
        ),
        migrations.DeleteModel(
            name='DepartmentConsumer',
        ),
        migrations.DeleteModel(
            name='DepartmentProvider',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
        migrations.DeleteModel(
            name='SystemConsumer',
        ),
        migrations.DeleteModel(
            name='SystemProvider',
        ),
        migrations.DeleteModel(
            name='UniversityConsumer',
        ),
        migrations.DeleteModel(
            name='UniversityProvider',
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'permissions': (('can_write_sys', 'Can write sys'), ('can_write_uni', 'Can write uni'), ('can_write_clg', 'Can write clg'), ('can_write_dpt', 'Can write dpt'))},
        ),
    ]
