# Generated by Django 2.2.10 on 2020-05-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insert2DB', '0002_auto_20200423_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='HigherEdDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=200)),
                ('collegeName', models.TextField(max_length=200)),
                ('departmentName', models.TextField(max_length=200)),
                ('universityName', models.TextField(max_length=200)),
                ('amountOfStudents', models.CharField(max_length=200)),
                ('pubDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='predictionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniqueID', models.TextField(max_length=200)),
                ('userProvider', models.TextField(max_length=200)),
                ('typeOfData', models.TextField(max_length=200)),
                ('sigma', models.IntegerField()),
                ('alpha', models.IntegerField()),
                ('beta', models.IntegerField()),
                ('lmbda', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
