# Generated by Django 2.2.10 on 2020-02-15 19:48

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insert2DB', '0005_auto_20200215_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='dptAdmin',
            fields=[
                ('teacher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insert2DB.Teacher')),
            ],
            options={
                'permissions': (('can_upload', 'Friendly message'),),
            },
            bases=('insert2DB.teacher',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': (('is_member', 'can_view'),)},
        ),
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('dptadmin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insert2DB.dptAdmin')),
            ],
            options={
                'permissions': (('can_view_school', 'Friendly message'),),
            },
            bases=('insert2DB.dptadmin',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Chancellor',
            fields=[
                ('dean_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insert2DB.Dean')),
            ],
            options={
                'permissions': (('can_view_all', 'Friendly message'),),
            },
            bases=('insert2DB.dean',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
